from schema import Season


def createSeasons():
    Season.create(
        season_id=2023,
        season_link='https://www.nzs.si/tekmovanja/default.asp?id_menu=300&id_sezone=2023',
        clubs_link='https://www.nzs.si/tekmovanja/default.asp?action=klubi&id_menu=721&id_sezone=2023',
        statistics_link='https://www.nzs.si/tekmovanja/default.asp?action=klub&id_menu=721&id_kluba=277&prikaz=5&id_sezone=2023',
        scoreboard_link='https://www.nzs.si/tekmovanja/default.asp?action=lestvica&id_menu=301&id_sezone=2023',
        description=None)
    Season.create(
        season_id=2022,
        season_link='https://www.nzs.si/tekmovanja/default.asp?id_menu=300&id_sezone=2022',
        clubs_link='https://www.nzs.si/tekmovanja/default.asp?action=klubi&id_menu=721&id_sezone=2022',
        statistics_link='https://www.nzs.si/tekmovanja/default.asp?action=klub&id_menu=721&id_kluba=277&prikaz=5&id_sezone=2022',
        scoreboard_link='https://www.nzs.si/tekmovanja/default.asp?action=lestvica&id_menu=301&id_sezone=2022',
        description=None)
    Season.create(
        season_id=2021,
        season_link='https://www.nzs.si/tekmovanja/default.asp?id_menu=300&id_sezone=2021',
        clubs_link='https://www.nzs.si/tekmovanja/default.asp?action=klubi&id_menu=721&id_sezone=2021',
        statistics_link='https://www.nzs.si/tekmovanja/default.asp?action=klub&id_menu=721&id_kluba=277&prikaz=5&id_sezone=2021',
        scoreboard_link='https://www.nzs.si/tekmovanja/default.asp?action=lestvica&id_menu=301&id_sezone=2021',
        description=None)
    Season.create(
        season_id=2020,
        season_link='https://www.nzs.si/tekmovanja/default.asp?id_menu=300&id_sezone=2020',
        clubs_link='https://www.nzs.si/tekmovanja/default.asp?action=klubi&id_menu=721&id_sezone=2020',
        statistics_link='https://www.nzs.si/tekmovanja/default.asp?action=klub&id_menu=721&id_kluba=277&prikaz=5&id_sezone=2020',
        scoreboard_link='https://www.nzs.si/tekmovanja/default.asp?action=lestvica&id_menu=301&id_sezone=2020',
        description=None)
    Season.create(
        season_id=2019,
        season_link='https://www.nzs.si/tekmovanja/default.asp?id_menu=300&id_sezone=2019',
        clubs_link='https://www.nzs.si/tekmovanja/default.asp?action=klubi&id_menu=721&id_sezone=2019',
        statistics_link='https://www.nzs.si/tekmovanja/default.asp?action=klub&id_menu=721&id_kluba=277&prikaz=5&id_sezone=2019',
        scoreboard_link='https://www.nzs.si/tekmovanja/default.asp?action=lestvica&id_menu=301&id_sezone=2019',
        description=None)
    Season.create(
        season_id=2018,
        season_link='https://www.nzs.si/tekmovanja/default.asp?id_menu=300&id_sezone=2018',
        clubs_link='https://www.nzs.si/tekmovanja/default.asp?action=klubi&id_menu=721&id_sezone=2018',
        statistics_link='https://www.nzs.si/tekmovanja/default.asp?action=klub&id_menu=721&id_kluba=277&prikaz=5&id_sezone=2018',
        scoreboard_link='https://www.nzs.si/tekmovanja/default.asp?action=lestvica&id_menu=301&id_sezone=2018',
        description=None)
    Season.create(
        season_id=2017,
        season_link='https://www.nzs.si/tekmovanja/default.asp?id_menu=300&id_sezone=2017',
        clubs_link='https://www.nzs.si/tekmovanja/default.asp?action=klubi&id_menu=721&id_sezone=2017',
        statistics_link='https://www.nzs.si/tekmovanja/default.asp?action=klub&id_menu=721&id_kluba=277&prikaz=5&id_sezone=2017',
        scoreboard_link='https://www.nzs.si/tekmovanja/default.asp?action=lestvica&id_menu=301&id_sezone=2017',
        description=None)
    Season.create(
        season_id=2016,
        season_link='https://www.nzs.si/tekmovanja/default.asp?id_menu=237&id_sezone=2016',
        clubs_link='https://www.nzs.si/tekmovanja/default.asp?action=klubi&id_menu=581&id_sezone=2016',
        statistics_link='https://www.nzs.si/tekmovanja/default.asp?action=klub&id_menu=581&id_kluba=277&prikaz=5&id_sezone=2016',
        scoreboard_link='https://www.nzs.si/tekmovanja/default.asp?action=lestvica&id_menu=238&id_sezone=2016',
        description=None)
    Season.create(
        season_id=2015,
        season_link='https://www.nzs.si/tekmovanja/default.asp?id_menu=237&id_sezone=2015',
        clubs_link='https://www.nzs.si/tekmovanja/default.asp?action=klubi&id_menu=581&id_sezone=2015',
        statistics_link='https://www.nzs.si/tekmovanja/default.asp?action=klub&id_menu=581&id_kluba=277&prikaz=5&id_sezone=2015',
        scoreboard_link='https://www.nzs.si/tekmovanja/default.asp?action=lestvica&id_menu=238&id_sezone=2015',
        description=None)
    Season.create(
        season_id=2014,
        season_link='https://www.nzs.si/tekmovanja/default.asp?id_menu=300&id_sezone=2014',
        clubs_link='https://www.nzs.si/tekmovanja/default.asp?action=klubi&id_menu=721&id_sezone=2014',
        statistics_link=None,
        scoreboard_link='https://www.nzs.si/tekmovanja/default.asp?action=lestvica&id_menu=301&id_sezone=2014',
        description=None)
    Season.create(
        season_id=2013,
        season_link='https://www.nzs.si/tekmovanja/default.asp?id_menu=300&id_sezone=2013',
        clubs_link='https://www.nzs.si/tekmovanja/default.asp?action=klubi&id_menu=721&id_sezone=2013',
        statistics_link=None,
        scoreboard_link='https://www.nzs.si/tekmovanja/default.asp?action=lestvica&id_menu=301&id_sezone=2013',
        description=None)
    
# createSeasons()